import {esc,table,action} from '../product-ui.js';import {filtersMarkup,wireFilters} from './results.js';
import {compactRows,toCsv,xlsxBlob,exportSheets,downloadBlob,auditZip,zipWithManifest} from '../../services/export-service.js';import {reportData,makePdf} from '../../services/report-service.js';import {selectResults,bulkScopes} from '../../views/result-model.js';
export function mountReports({main,model,filter,synthetic,onChange}){
 main.innerHTML=`<div data-reports-root><h1>Reports & exports</h1><p class="lead">Every result export and PDF uses the same selected scope as Results. Source values retain full precision; missing values stay blank.</p>${filtersMarkup(model,filter)}<section class="card"><h2>Result workbooks</h2><div class="sample-actions"><button class="button secondary" data-export="csv">Compact CSV</button><button class="button secondary" data-export="compact">Compact XLSX</button><button class="button secondary" data-export="management">Management XLSX</button><button class="button secondary" data-export="technical">Technical/M&E XLSX</button></div></section><section class="card"><h2>PDF report</h2><label>Audience<select data-report-mode><option value="management">Management</option><option value="technical">Technical / M&E</option></select></label><p>Project, district, block, GP, village and structure reports follow the selected geography.</p><button class="button" data-pdf>Download PDF</button><p role="status" data-report-status></p></section><section class="card"><h2>Audit and bulk download</h2><p>The Standard Audit JSON covers the complete run and excludes raw workbook bytes and participant names. Bulk bundles contain one PDF per selected-level geography within the current scope.</p><div class="sample-actions"><button class="button secondary" data-audit-json>Standard Audit JSON</button><button class="button secondary" data-audit-zip>Audit package ZIP</button></div><label>Bulk report level<select data-bulk-level><option value="district">District</option><option value="block">Block</option><option value="gram_panchayat">GP</option><option value="village">Village</option><option value="structure">Structure</option></select></label><button class="button secondary" data-bulk>Download report bundle ZIP</button><button class="button secondary" data-combined-pdf>Download combined PDF</button></section><section class="card"><h2>Included result records</h2>${table(compactRows(model,filter,synthetic),[{key:'recordId',label:'Record'},{key:'component',label:'Component'},{key:'result',label:'Result'},{key:'unit',label:'Unit'},{key:'assurance',label:'Assurance'}])}</section></div>`;
 wireFilters(main,filter,onChange);
 for(const button of main.querySelectorAll('[data-export]'))action(main,`[data-export="${button.dataset.export}"]`,async()=>{const kind=button.dataset.export;if(kind==='csv')downloadBlob(new Blob([toCsv(compactRows(model,filter,synthetic))],{type:'text/csv;charset=utf-8'}),'HUF_Compact_Results.csv');else downloadBlob(await xlsxBlob(exportSheets(model,filter,synthetic,kind)),`HUF_${kind}_Results.xlsx`);});
 action(main,'[data-pdf]',()=>{const d=reportData(model,filter,synthetic,main.querySelector('[data-report-mode]').value);const doc=makePdf(d);downloadBlob(doc.output('blob'),'HUF_'+d.metadata.scope?.label+'_Report.pdf');main.querySelector('[data-report-status]').textContent='Report generated from '+d.metadata.includedResultIds.length+' prepared result records.';});
 action(main,'[data-audit-json]',()=>downloadBlob(new Blob([JSON.stringify(model.pack.audit,null,2)],{type:'application/json'}),'HUF_Standard_Audit.json'));
 action(main,'[data-audit-zip]',async()=>downloadBlob(await auditZip(model),'HUF_Audit_Package.zip'));
 const bulkData=()=>bulkScopes(model,filter,main.querySelector('[data-bulk-level]').value).map(s=>reportData(model,s.filter,synthetic,main.querySelector('[data-report-mode]').value));
 action(main,'[data-bulk]',async()=>{const reports=bulkData();if(!reports.length)throw new Error('No matching geographies at this level.');const files={};reports.forEach((d,i)=>{files[`${String(i+1).padStart(3,'0')}_${d.metadata.scope.label.replace(/[^\p{L}\p{N}_ -]/gu,'_')}.pdf`]=makePdf(d).output('arraybuffer');});files['scope-results.csv']=toCsv(compactRows(model,filter,synthetic));files['SCOPES.json']=JSON.stringify(reports.map(d=>d.metadata),null,2);downloadBlob(await zipWithManifest(files,{runId:model.pack.audit.runManifest.runId,filters:filter,synthetic}),'HUF_Report_Bundle.zip');});
 action(main,'[data-combined-pdf]',()=>{const reports=bulkData();if(!reports.length)throw new Error('No matching geographies at this level.');downloadBlob(makePdf(reports).output('blob'),'HUF_Combined_Report.pdf');});
}
