import fs from 'node:fs/promises';import assert from 'node:assert/strict';import crypto from 'node:crypto';import JSZip from 'jszip';
const root=new URL('../../',import.meta.url),read=async p=>JSON.parse(await fs.readFile(new URL(p,root),'utf8'));
const regression=await read('tests/evidence/protected-regression.json'),remaining=await read('tests/evidence/design6-remaining80.json');assert.equal(regression.status,'PASS');assert.equal(remaining.status,'PASS');assert.equal(remaining.total,80);
const suite=name=>regression.suites.find(s=>s.name===name).evidence;
const e06=suite('node-engine06.mjs'),d5=suite('node-design6-d5.mjs'),physical=suite('node-engine04-fixtures.mjs');
const formulas=[...new Set(e06.checks.filter(c=>/^G-\d{3}/.test(c.id)&&c.status==='PASS').map(c=>c.id.match(/^G-(\d{3})/)[1]))];assert.equal(formulas.length,29);assert.equal(d5.checks.filter(c=>c.status==='PASS').length,28);assert.equal(physical.cases.filter(c=>c.status==='PASS').length,15);
const e2e=['E2E_','LEAP_'].map(prefix=>{const cases=e06.checks.filter(c=>c.id.startsWith(prefix));assert.equal(cases.length,17);assert.ok(cases.every(c=>c.status==='PASS'));return {prefix,status:'PASS',assertions:cases.length};});
const zip=await JSZip.loadAsync(await fs.readFile(new URL('tests/protected/baseline-tests.zip',root)));const manifest=JSON.parse(await zip.file('tests/design6/frozen/HUF_Design6_Physical_Fixture_Manifest_v1.0.json').async('string'));
const hashes=physical.cases.map(c=>({file:c.file,sha256:null,status:'PENDING'}));
// Match each freshly executed physical file to the unchanged Design-6 duplicate in the frozen bundle.
for(const item of hashes){const actual=await zip.file('tests/fixtures/engine04/'+item.file).async('nodebuffer'),frozen=await zip.file('tests/design6/frozen/fixtures/negative_high_risk/'+item.file).async('nodebuffer');assert.deepEqual(actual,frozen);item.sha256=crypto.createHash('sha256').update(actual).digest('hex');assert.equal(item.sha256,manifest.find(f=>f.file.endsWith('/'+item.file)).sha256);item.status='PASS';}
const result={schema:'HUF-D6-FRESH-LOGICAL-ASSESSMENT-v1',methodologyChanged:false,logicalTests:{total:154,pass:154,fail:0,notVerified:0,bySuite:{positiveGolden:2,formulaGolden:29,physicalRuleCases:15,remainingRuleCases:80,outputSchema:28}},physicalFixtures:{total:15,pass:15,hashes},positiveGolden:e2e,calculationInjectionBoundary:'VAL-063/086/087/088 use the frozen test-only prepared-state injection/tolerance oracle. These do not assert that production accepts arbitrary mutated daily snapshots.',browserAcceptance:'SEPARATE_REQUIRED_GATE',deploymentAcceptance:'SEPARATE_REQUIRED_GATE',formalHufConfirmation:'SEPARATE_GOVERNANCE'};await fs.writeFile(new URL('tests/evidence/design6-logical.json',root),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.logicalTests));
