import fs from 'node:fs/promises';import {performance} from 'node:perf_hooks';import {runFixture,createFixtureAdapter} from '../fixtures/runtime.mjs';import {xlsxBlob} from '../../services/export-service.js';import {createResultModel,selectResults} from '../../views/result-model.js';
const original=await runFixture(),detail=original.getPreparationDetail();const outputs=[];
// Synthetic capacity probe only: this does not establish the user's production portfolio or acceptance budget.
for(const factor of [5,50]){
 const sheetRows={};for(const table of detail.tables){const shared=['01_Control','06_Daily_Rainfall','07_Hydro_Params'].includes(table.expectedSheet),rows=[];for(let copy=0;copy<(shared?1:factor);copy++)for(const r of table.records){const values={};for(const c of Object.values(r.cells)){let value=c.sourceValue;if(typeof value==='string'&&!shared){if(/^S-/.test(value)||/^PD-\d/.test(value)||/^P-\d/.test(value)||/^CAT-/.test(value)||/^CSL-/.test(value)||/^EVD-/.test(value)||/^SIL-/.test(value)||/^STA-/.test(value))value+='-COPY'+copy;}values[c.sourceHeader]=value;}rows.push(values);}sheetRows[table.expectedSheet]=rows;}
 const blob=await xlsxBlob(sheetRows),bytes=await blob.arrayBuffer(),adapter=await createFixtureAdapter(),timings={};let now=performance.now();await adapter.runIntake(new File([bytes],`SYNTHETIC_PERFORMANCE_${factor*20}.xlsx`));timings.intakeMs=performance.now()-now;now=performance.now();await adapter.buildMapping();await adapter.confirmAllSuggested();await adapter.confirmMapping();timings.mappingMs=performance.now()-now;for(const stage of ['E03','E04','E05','E06','E07','E08','E09']){now=performance.now();await adapter.runStage(stage);timings[stage+'Ms']=performance.now()-now;}
 now=performance.now();const model=createResultModel(adapter.getResultPackage());for(let i=0;i<50;i++)selectResults(model,{scope:model.scopes[i%model.scopes.length].key});timings.viewPreparationAnd50QueriesMs=performance.now()-now;
 outputs.push({synthetic:true,representativeProductionFixture:false,structures:factor*20,personDayRecords:factor*20,rainfallRows:365,bytes:bytes.byteLength,calculatedWaterResults:model.pack.calculation.stats.calculatedWaterResults,aggregationStatus:model.pack.aggregation.status,timings,peakRssBytes:process.resourceUsage().maxRSS*1024});console.log(JSON.stringify(outputs.at(-1)));
}
await fs.writeFile(process.env.HUF_PERFORMANCE_PROBE_PATH||'/tmp/huf-performance-probe.json',JSON.stringify({schema:'HUF-SYNTHETIC-CAPACITY-PROBE-v1',status:'MEASURED_NOT_PRODUCTION_ACCEPTANCE',environment:'Node runtime; browser responsiveness and production scale require separate acceptance',budget:null,results:outputs},null,2)+'\n');
