import fs from 'node:fs/promises';import crypto from 'node:crypto';import assert from 'node:assert/strict';import JSZip from 'jszip';
import {runFixture} from '../fixtures/runtime.mjs';
import {evaluateValidation,dateRange} from '../../protected-core/js/engines/engine04-validation.js';
import {evaluateRouting} from '../../protected-core/js/engines/engine05-routing.js';
import {evaluateCalculation} from '../../protected-core/js/engines/engine06-calculation.js';
import {evaluateAssurance} from '../../protected-core/js/engines/engine07-assurance.js';
import {evaluateAggregation} from '../../protected-core/js/engines/engine08-aggregation.js';
import {numericTolerance,withinTolerance,kpi111} from '../../protected-core/js/engines/engine06-formulas.js';
const json=async p=>JSON.parse(await fs.readFile(new URL(p,import.meta.url),'utf8'));
const config={};for(const [key,file] of Object.entries({inputSchema:'input-schema-v1.1',rulebook:'validation-rulebook-v1.0',routeRegistry:'route-registry-v1.1',routingPolicy:'routing-policy-v1.0',formulaCatalog:'formula-catalog-v1.1',assurancePolicy:'assurance-policy-v1.0',aggregationPolicy:'aggregation-policy-v1.0'}))config[key]=await json('../../protected-core/config/'+file+'.json');
const archive=await JSZip.loadAsync(await fs.readFile(new URL('baseline-tests.zip',import.meta.url)));const registry=JSON.parse(await archive.file('tests/design6/frozen/HUF_Design6_Scenario_Builder_Registry_v1.0.json').async('string'));
const non=await runFixture(),leap=await runFixture('leap/GOLDEN_E2E_LEAP_FY2023-24.xlsx');const pack=non.getResultPackage(),lp=leap.getResultPackage();
const baseline={...non.getPublicProtectedState().canonicalization,tables:non.getPreparationDetail().tables,diagnostics:[]};
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');const baselineHash=hash(baseline),calculationHash=hash(pack.calculation);
const table=(c,name)=>c.tables.find(t=>t.expectedSheet===name);const record=(c,name,key,id)=>table(c,name).records.find(r=>r.values[key]===id);const first=(c,name)=>table(c,name).records[0];
const set=(r,key,value)=>{r.values[key]=value;if(r.cells?.[key])r.cells[key].canonicalValue=value;};
const s=c=>first(c,'02_Structures'),t=c=>first(c,'03_Technical'),ctl=c=>first(c,'01_Control'),cat=c=>first(c,'04_Catchments'),rain=c=>first(c,'06_Daily_Rainfall'),hyd=c=>first(c,'07_Hydro_Params'),ev=c=>first(c,'11_Evidence');
const pd=(c,category)=>table(c,'10_Person_Days').records.find(r=>r.values['PD-007']===category);
const sil=c=>{let r=first(c,'09_Silt_Assessment');if(!r){r={values:{'SIL-001':'D6-SILT','SIL-002':'S-CCT-01'},cells:{},sourceRowNumber:2};table(c,'09_Silt_Assessment').records.push(r);}return r;};
function stage(c,count=2){set(t(c),'TEC-023','Advanced stage-area');set(t(c),'TEC-024','D6-STAGE');table(c,'08_Stage_Area_Optional').records=Array.from({length:count},(_,i)=>({values:{'STA-001':'D6-STAGE-'+i,'STA-002':'D6-STAGE','STA-003':'S-CCT-01','STA-004':i,'STA-005':60+i*10,'STA-006':30},cells:{},sourceRowNumber:i+2}));}
const noEvidence=c=>{table(c,'11_Evidence').records=table(c,'11_Evidence').records.filter(r=>r.values['EVD-003']!=='S-WAT-01');};
const mutations={
 '001':c=>set(ctl(c),'CTL-001','unsupported'), '002':c=>table(c,'01_Control').records.push(structuredClone(ctl(c))), '003':c=>set(ctl(c),'CTL-002',null), '004':c=>set(ctl(c),'CTL-005','2026-04-01'), '005':c=>set(ctl(c),'CTL-005','2024-04-02'), '009':c=>set(ctl(c),'CTL-010','unsupported'), '010':c=>set(ctl(c),'CTL-011',null),
 '011':c=>set(t(c),'TEC-023','invalid'), '012':c=>set(ctl(c),'CTL-012',null), '013':()=>{}, '014':c=>table(c,'02_Structures').records.push(structuredClone(s(c))), '015':c=>table(c,'04_Catchments').records.push(structuredClone(cat(c))), '016':c=>set(t(c),'TEC-001','MISSING'), '017':c=>set(t(c),'TEC-017','MISSING'), '018':c=>set(t(c),'TEC-022','MISSING'), '020':c=>set(ev(c),'EVD-003','MISSING'),
 '021':c=>set(s(c),'STR-003','Unknown'), '022':c=>set(s(c),'STR-005','Unknown'), '023':c=>set(s(c),'STR-006','Unknown'), '024':c=>set(s(c),'STR-007',null), '032':c=>set(table(c,'02_Structures').records.find(r=>r.values['STR-005']==='Rejuvenation/repair'),'STR-020',null),
 '035':c=>{const r=table(c,'02_Structures').records.find(r=>r.values['STR-020']==='Post-intervention minus baseline capacity');set(record(c,'03_Technical','TEC-001',r.values['STR-001']),'TEC-014',1);},
 '036':c=>set(t(c),'TEC-005',0), '037':c=>{set(t(c),'TEC-007','Slope-estimated');set(t(c),'TEC-008',null);}, '038':c=>set(s(c),'STR-003','Unknown'), '039':c=>set(t(c),'TEC-011',999999), '040':c=>{table(c,'04_Catchments').records=table(c,'04_Catchments').records.filter(r=>r.values['CAT-002']!=='S-CCT-01');}, '041':c=>{set(cat(c),'CAT-003','Method 2 - 20% intercepted');set(cat(c),'CAT-006',null);}, '042':c=>set(cat(c),'CAT-005',-1), '044':c=>{const r=first(c,'05_Cascade_Links');set(r,'CSL-003',r.values['CSL-002']);},
 '046':c=>set(rain(c),'RAN-003','invalid'), '048':c=>set(rain(c),'RAN-004',null), '051':c=>{set(t(c),'TEC-018','Nearest station');set(s(c),'STR-015',100);}, '052':c=>{set(t(c),'TEC-018','Same hydrological/administrative zone');set(s(c),'STR-014','Different zone');}, '053':c=>{set(t(c),'TEC-018','Documented expert selection');set(t(c),'TEC-019',null);}, '054':c=>table(c,'07_Hydro_Params').records.push(structuredClone(hyd(c))), '057':c=>set(hyd(c),'HYP-002',-1), '058':c=>set(hyd(c),'HYP-002',200), '061':c=>set(hyd(c),'HYP-005',100), '062':c=>{set(t(c),'TEC-020',null);set(t(c),'TEC-002',null);}, '064':c=>stage(c,1), '065':c=>{stage(c);set(table(c,'08_Stage_Area_Optional').records[1],'STA-005',1);}, '066':c=>{stage(c);set(table(c,'08_Stage_Area_Optional').records[1],'STA-004',0.0001);},
 '067':c=>set(sil(c),'SIL-002','S-CCT-01'), '068':c=>{set(sil(c),'SIL-004','Physical 5-point assessment');set(sil(c),'SIL-006',null);}, '069':c=>{const r=sil(c);set(r,'SIL-004','Physical 5-point assessment');set(r,'SIL-005',1);for(let i=6;i<=10;i++)set(r,'SIL-'+String(i).padStart(3,'0'),2);}, '070':c=>{set(sil(c),'SIL-004','Year-3 cumulative assumption');set(sil(c),'SIL-011',101);}, '071':c=>{set(sil(c),'SIL-004','Surveyed volume loss');set(sil(c),'SIL-012',1e9);}, '072':c=>{const r=sil(c),sid=r.values['SIL-002'];set(r,'SIL-013','2024-05-01');table(c,'11_Evidence').records=table(c,'11_Evidence').records.filter(e=>![sid,r.values['SIL-001']].includes(e.values['EVD-003']));}, '074':noEvidence, '075':c=>set(ev(c),'EVD-006',null), '076':c=>table(c,'10_Person_Days').records.push(structuredClone(first(c,'10_Person_Days'))), '077':c=>set(first(c,'10_Person_Days'),'PD-004','2020-01-01'), '078':c=>set(pd(c,'Paid labour'),'PD-009',-1), '079':c=>set(pd(c,'Community contribution'),'PD-008',-1), '080':c=>set(pd(c,'Volume-based estimate'),'PD-010',0), '081':c=>set(pd(c,'Machinery-support labour'),'PD-013',null), '083':c=>{const v=pd(c,'Volume-based estimate'),d=pd(c,'Paid labour');set(v,'PD-002',d.values['PD-002']);set(v,'PD-003',d.values['PD-003']);}, '085':c=>{set(t(c),'TEC-002',null);c.diagnostics.push({expectedSheet:'03_Technical',sourceRowNumber:t(c).sourceRowNumber,fieldId:'TEC-002',code:'NUMERIC_INVALID',detail:'Test mutation preserves unparseable source as null'});}
};
const validation=c=>evaluateValidation({canonicalSnapshot:c,...config});
async function through(c){const v=validation(c),r=await evaluateRouting({canonicalSnapshot:c,validationSnapshot:v,...config}),calc=await evaluateCalculation({canonicalSnapshot:c,validationSnapshot:v,routingSnapshot:r,...config}),a=await evaluateAssurance({canonicalSnapshot:c,validationSnapshot:v,routingSnapshot:r,calculationSnapshot:calc,...config});return {v,r,calc,a};}
const w=(p,id)=>p.waterCalculations.find(r=>r.structureRecordId===id);const route=id=>pack.routing.waterRoutes.find(r=>r.structureRecordId===id);const ready=(v,id)=>v.structureReadiness.find(r=>r.structureRecordId===id)?.validationReadiness;
const result=[];
for(const spec of registry.filter(s=>s.execution_mode!=='WORKBOOK_PHYSICAL')){
 const id=spec.builder_id.slice(4),c=structuredClone(baseline);let detail={};try{
  if(mutations[id]){mutations[id](c);const v=validation(c);if(id==='066'){const downstream=await through(c);assert.equal(downstream.calc.calculationQa.ruleResults.find(r=>r.ruleId==='VAL-066').status,'FAIL');assert.equal(w(downstream.calc,'S-CCT-01').resultM3,null);detail={actualCalculationStatus:w(downstream.calc,'S-CCT-01').calculationStatus};}else{
    const found=v.issues.filter(i=>i.ruleId===spec.builder_id);assert.ok(found.length,'Expected issue not emitted');assert.ok(found.every(i=>i.severity===spec.expected_severity&&i.scopeEffect===spec.expected_scope_effect&&i.readinessEffect===spec.expected_readiness_effect),'Issue contract mismatch');
    const affected=new Set(v.issues.filter(i=>['BLOCKING_ERROR','SCOPED_ERROR'].includes(i.severity)).flatMap(i=>i.affectedStructureIds||[]));if(v.workbookReadiness==='workbook_not_ready')assert.ok(v.structureReadiness.every(r=>r.validationReadiness==='workbook_not_ready'));else for(const r of v.structureReadiness){if(!affected.has(r.structureRecordId)&&!['excluded','hold'].includes(r.validationReadiness))assert.notEqual(r.validationReadiness,'not_ready','Unrelated structure blocked');}
    detail={actualIssues:found.map(i=>({ruleId:i.ruleId,severity:i.severity,scopeEffect:i.scopeEffect,readinessEffect:i.readinessEffect,affectedStructureIds:i.affectedStructureIds})),workbookReadiness:v.workbookReadiness,scopeIsolation:'PASS'};
  }}else if(['006','007','008'].includes(id)){const dates=dateRange('2023-04-01','2024-03-31'),nonDates=dateRange('2024-04-01','2025-03-31');assert.equal(dates.length,366);assert.equal(nonDates.length,365);assert.ok(dates.includes('2024-02-29'));assert.ok(!nonDates.some(d=>d.endsWith('02-29')));assert.equal(lp.audit.runManifest.expectedCalendarDays,366);detail={leapDays:dates.length,nonLeapDays:nonDates.length};
  }else if(id==='025'){assert.equal(route('S-CCT-01').waterRouteId,'WTR-111-NEW');assert.equal(route('S-WAT-01').waterRouteId,'WTR-112-NEW');
  }else if(id==='027'){const def=ctl(c).values['CTL-009'];let overrides=0;for(const r of table(c,'02_Structures').records){const override=r.values['STR-019'];if(override)overrides++;const resolved=route(r.values['STR-001']).timingMethod;assert.ok(['Strict cutoff','Actual functional date - partial season'].includes(resolved));assert.equal(resolved,override||def);}assert.equal(overrides,1);detail={addendum:'HUF-D6-VAL027-POSITIVE-INVARIANT-v1.1',structures:20,overrides};
  }else if(['028','029','030'].includes(id)){const sid={'028':'S-GOV-01','029':'S-SUB-01','030':'S-FP-P-01'}[id];assert.equal(route(sid).eligibilityStatus,id==='030'?'hold':'excluded');assert.equal(w(pack.calculation,sid).resultM3,null);
  }else if(id==='060'){const n=w(pack.calculation,'S-CCT-01').dailyTrace,l=w(lp.calculation,'S-CCT-01').dailyTrace;assert.equal(n.find(d=>d.date==='2025-02-28').evaporationRateMmDay,4.5);assert.equal(l.find(d=>d.date==='2024-02-29').evaporationRateMmDay,4.5);assert.ok(!n.some(d=>d.date.endsWith('02-29')));
  }else if(['063','086','087','088'].includes(id)){
    // Test-only state injection and independent Design-2 tolerance oracle; protected snapshots stay immutable.
    const original=w(pack.calculation,'S-CCT-01'),injected=structuredClone(original),day=injected.dailyTrace[0];
    if(id==='063'){assert.ok(original.dailyTrace.every(d=>d.qa.areaBounds));day.fillFraction=2;day.evaporationAreaM2=1e9;assert.ok(day.fillFraction>1||day.evaporationAreaM2>original.capacity.storagePlanAreaM2);}
    if(id==='086'){assert.ok(original.dailyTrace.every(d=>d.qa.nonnegative));day.closingStorageM3=-1;assert.ok(day.closingStorageM3 < -numericTolerance(day.closingStorageM3,0));}
    if(id==='087'){assert.ok(original.dailyTrace.every(d=>d.qa.massPass));day.closingStorageM3+=1;const residual=day.previousClosingStorageM3+day.generatedRunoffM3-day.overflowM3-day.actualEvaporationM3-day.actualInfiltrationM3-day.closingStorageM3;assert.ok(!withinTolerance(residual,0));}
    if(id==='088'){assert.ok(original.qa.identityPass);injected.cumulativeInfiltrationM3+=1;const identity=kpi111({captured:injected.capturedRunoffM3,evaporation:injected.cumulativeEvaporationM3,infiltration:injected.cumulativeInfiltrationM3,finalClosing:injected.finalClosingStorageM3});assert.ok(!withinTolerance(identity.primary,identity.crosscheck));}
    detail={injectionDetected:true,assertionBoundary:'Test-only prepared-state oracle; does not claim production re-execution of injected daily state'};
  }else if(id==='089'){const v=w(pack.calculation,'S-CCT-01');assert.equal(v.resultM3,228.5841281366329);assert.ok(withinTolerance(v.resultM3,v.identityCrosscheckM3));assert.notEqual(v.resultM3,Number(v.resultM3.toFixed(3)));
  }else if(['090','091'].includes(id)){const a=structuredClone(pack.assurance);if(id==='090')a.waterAssurance.find(r=>r.assuranceStatus==='excluded').assuranceStatus='accepted-certified';else a.waterAssurance.push(structuredClone(a.waterAssurance[0]));const outcome=await evaluateAggregation({canonicalSnapshot:c,calculationSnapshot:pack.calculation,assuranceSnapshot:a,...config});assert.equal(outcome.aggregationQa.ruleResults.find(r=>r.ruleId===spec.builder_id).status,'FAIL');assert.equal(outcome.status,'aggregation_not_ready');detail={actualAggregationStatus:outcome.status};
  }else if(id==='092'){const v=validation(c);assert.equal(ready(v,'S-FP-P-01'),'hold');assert.equal(ready(v,'S-GOV-01'),'excluded');assert.equal(ready(v,'S-CCT-01'),'ready_with_warning');assert.equal(ready(v,'S-WAT-01'),'ready');
  }else if(['084','093'].includes(id)){set(rain(c),'RAN-004',-1);const d=await through(c);assert.equal(w(d.calc,'S-CCT-01').resultM3,null);assert.equal(w(d.calc,'S-WAT-01').resultM3,w(pack.calculation,'S-WAT-01').resultM3);assert.deepEqual(d.calc.personDayCalculations.map(r=>r.calculatedPersonDays),pack.calculation.personDayCalculations.map(r=>r.calculatedPersonDays));assert.equal(w(d.calc,'S-MW-01').calculationStatus,'calculated');detail={affectedStructureCount:d.v.issues.find(i=>i.ruleId==='VAL-047').affectedStructureIds.length};assert.equal(detail.affectedStructureCount,10);
  }else if(id==='094'){set(t(c),'TEC-021',null);const d=await through(c);assert.equal(w(d.calc,'S-CCT-01').calculationStatus,'not_calculated_not_ready');assert.equal(w(d.calc,'S-CD-01').calculationStatus,'not_calculated_dependency');assert.equal(w(d.calc,'S-SCT-01').calculationStatus,'calculated');
  }else if(id==='095'){noEvidence(c);const d=await through(c);assert.equal(w(d.calc,'S-WAT-01').resultM3,w(pack.calculation,'S-WAT-01').resultM3);assert.equal(d.a.waterAssurance.find(r=>r.structureRecordId==='S-WAT-01').assuranceStatus,'provisional-evidence-pending');
  }else throw new Error('Scenario not implemented');
  assert.equal(hash(baseline),baselineHash);assert.equal(hash(pack.calculation),calculationHash);
  result.push({test_id:'D4-'+spec.builder_id,status:'PASS',executionMode:id==='027'?'POSITIVE_INVARIANT_ASSERTION':spec.execution_mode,expectedReference:'Frozen Scenario Builder Registry; VAL-027 v1.1 addendum',upstreamTruthPreserved:true,...detail});
 }catch(error){result.push({test_id:'D4-'+spec.builder_id,status:'FAIL',error:error.message,...detail});}
}
const failures=result.filter(r=>r.status!=='PASS');const out={schema:'HUF-D6-FRESH-REMAINING80-v1',status:failures.length?'FAIL':'PASS',total:result.length,passed:result.length-failures.length,failed:failures.length,methodologyChanged:false,results:result};await fs.writeFile(new URL('../evidence/design6-remaining80.json',import.meta.url),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({...out,results:failures},null,2));if(failures.length)process.exitCode=1;
