import {selectResults,summarizeResults,scopeMetadata} from '../views/result-model.js';
export function downloadBlob(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name.replace(/[^\p{L}\p{N}_. -]/gu,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export function safeSpreadsheetText(value){const s=String(value??'');return /^[\s]*[=+@-]/.test(s)?"'"+s:s;}
export function toCsv(rows){const keys=[...new Set(rows.flatMap(Object.keys))];const cell=v=>{const x=typeof v==='number'?String(v):safeSpreadsheetText(typeof v==='object'&&v!==null?JSON.stringify(v):v);return '"'+x.replaceAll('"','""')+'"';};return '\ufeff'+[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');}
export function design5Rows(model,filter){const runId=model.pack.audit.runManifest.runId;const rows=selectResults(model,filter);return {
 WaterResults:rows.filter(r=>r.type==='water').map(r=>{const c=r.calculation,i=r.identity,a=r.assurance;return {waterResultId:r.resultId,runId,structureRecordId:r.recordId,structureName:r.name,structureType:r.structureType,structureSubtype:i['STR-004'],interventionType:i['STR-005'],liningStatus:i['STR-006'],waterRouteId:r.route,waterComponent:r.component,calculationReadiness:a.calculationReadiness,calculationStartDate:c.calculationStartDate,calculationEndDate:c.calculationEndDate,calculationDays:c.calculationDays,state:i['STR-009'],district:i['STR-010'],block:i['STR-011'],gramPanchayat:i['STR-012'],village:i['STR-013'],grossPhysicalCapacityM3:c.capacity?.grossCapacityM3??null,siltLossM3:c.capacity?.siltLossM3??null,appliedSiltFraction:c.capacity?.appliedSiltFraction??null,netPhysicalCapacityM3:c.capacity?.netCapacityM3??null,eligibleAttributableCapacityM3:c.capacity?.eligibleCapacityM3??null,effectiveCatchmentHa:c.catchment?.effectiveHa??null,generatedRunoffM3:c.generatedRunoffM3??null,overflowM3:c.overflowM3??null,capturedRunoffM3:c.capturedRunoffM3??null,cumulativeEvaporationM3:c.cumulativeEvaporationM3??null,cumulativeInfiltrationM3:c.cumulativeInfiltrationM3??null,finalClosingStorageM3:c.finalClosingStorageM3??null,waterResultM3:c.resultM3,waterResultBL:c.resultBL,identityCrosscheckM3:c.identityCrosscheckM3??null,identityDifferenceM3:c.identityDifferenceM3??null,residualRunoffFraction:c.residualRunoffFraction??null,maxMassResidualM3:c.maxMassResidualM3??null,formulaIds:c.formulaIds,formulaCatalogVersion:model.pack.audit.runManifest.formulaCatalogVersion,capacityCatalogVersion:model.pack.audit.runManifest.capacityCatalogVersion,validationRulebookVersion:model.pack.audit.runManifest.validationRulebookVersion};}),
 PersonDayResults:rows.filter(r=>r.type==='person-day').map(r=>{const s=r.sourceBasis||{};return {personDayResultId:r.resultId,runId,personDayRecordId:r.recordId,structureWorkId:r.structureId,workScope:s['PD-003'],category:s['PD-007'],calculationMethod:r.route,workDate:s['PD-004'],gender:s['PD-006'],sourceHours:s['PD-008'],sourceDirectDays:s['PD-009'],sourceWorkQuantity:s['PD-010'],quantityUnit:s['PD-011'],productivityNorm:s['PD-012'],machinerySupportRole:s['PD-013'],calculatedPersonDays:r.value,calculationReadiness:r.assurance.calculationReadiness,formulaIds:r.calculation.formulaIds};}),
 Assurance:rows.map(r=>({runId,...r.assurance,publicAssuranceLabel:r.statusLabel}))};}
export function compactRows(model,filter,synthetic){const m=scopeMetadata(model,filter,synthetic),d=design5Rows(model,filter),byId=new Map([...d.WaterResults.map(r=>[r.waterResultId,r]),...d.PersonDayResults.map(r=>[r.personDayResultId,r])]);return selectResults(model,filter).map(r=>({...byId.get(r.resultId),runId:m.runId,scope:m.scope?.key,filters:JSON.stringify(m.filters),generatedAt:new Date().toISOString(),synthetic:m.synthetic,resultId:r.id,recordId:r.recordId,component:r.component,officialRoute:r.route,assuranceStatus:r.status,assurance:r.statusLabel,evidenceCompleteness:r.assurance.evidenceCompleteness,result:r.value,unit:r.unit,formalHufConfirmation:m.formalHufConfirmation,methodology:JSON.stringify(m.methodology)}));}
export function traceExport(model,row,synthetic){const metadata=scopeMetadata(model,{resultIds:[row.id]},synthetic);return {metadata,structureRecordId:row.recordId,waterRouteId:row.route,rows:row.calculation.dailyTrace||[]};}
export function traceCsv(model,row,synthetic){const d=traceExport(model,row,synthetic);return toCsv(d.rows.map(r=>({runId:d.metadata.runId,structureRecordId:row.recordId,synthetic:Boolean(synthetic),reportingStartDate:d.metadata.reportingStartDate,reportingEndDate:d.metadata.reportingEndDate,formulaCatalogVersion:model.pack.audit.runManifest.formulaCatalogVersion,...r})));}
const xml=s=>String(s??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
const col=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
export async function xlsxBlob(sheets){
 const zip=new globalThis.JSZip();const names=Object.keys(sheets);
 zip.file('xl/styles.xml','<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF125469"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" applyAlignment="1"><alignment wrapText="1" vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="0" applyAlignment="1"><alignment wrapText="1" vertical="top"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>');
 const contentTypes=['<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>','<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>','<Default Extension="xml" ContentType="application/xml"/>','<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>',...names.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`)];
 zip.file('[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">${contentTypes.join('')}</Types>`);
 zip.file('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
 zip.file('xl/workbook.xml',`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${names.map((n,i)=>`<sheet name="${xml(n.slice(0,31))}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`);
 zip.file('xl/_rels/workbook.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>${names.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`);
 names.forEach((name,i)=>{const rows=sheets[name],keys=[...new Set(rows.flatMap(Object.keys))],data=[Object.fromEntries(keys.map(k=>[k,k])),...rows];zip.file(`xl/worksheets/sheet${i+1}.xml`,`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${keys.map((_,j)=>`<col min="${j+1}" max="${j+1}" width="24" customWidth="1"/>`).join('')}</cols><sheetData>${data.map((r,n)=>`<row r="${n+1}" ht="${n===0?38:45}" customHeight="1">${keys.map((k,j)=>{const v=r[k],ref=col(j)+(n+1);if(v===null||v===undefined)return `<c r="${ref}"/>`;if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}" t="n"><v>${v}</v></c>`;return `<c r="${ref}" s="${n===0?1:2}" t="inlineStr"><is><t xml:space="preserve">${xml(typeof v==='object'?JSON.stringify(v):v)}</t></is></c>`;}).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${col(Math.max(keys.length-1,0))}${data.length}"/></worksheet>`);});
 return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
}
export function exportSheets(model,filter,synthetic,mode){const meta=scopeMetadata(model,filter,synthetic),rows=selectResults(model,filter),d5=design5Rows(model,filter);const sheets={Metadata:Object.entries({...meta,generatedAt:new Date().toISOString(),contract:'HUF-D5-RESULT-AUDIT-REPORTING-v1.0; privacy-reduced default export'}).map(([key,value])=>({key,value:typeof value==='object'?JSON.stringify(value):value})),Results:compactRows(model,filter,synthetic),...d5};if(mode!=='compact'){sheets.Summary=summarizeResults(rows);const ids=new Set(rows.map(r=>r.id));sheets.Geography=model.scopes.flatMap(scope=>summarizeResults(rows.filter(r=>r.memberships.includes(scope.key))).map(summary=>({reportingKey:scope.key,reportingLevel:scope.level,reportingLabel:scope.label,parentReportingKey:scope.parent,...summary})));sheets.Register=compactRows(model,filter,synthetic).filter(r=>r.unit==='m3');sheets.Notes=[{note:'Calculated total = accepted + provisional + warning; null is not zero.'},{note:'Participant names/tokens and source notes are omitted from standard exports.'}];}if(mode==='technical'){sheets.Routes=rows.filter(r=>r.type==='water').map(r=>r.routeDetail);sheets.Validation=model.pack.audit.validationIssues.filter(i=>i.entityType==='workbook'||rows.some(r=>r.recordId===i.entityId||r.structureId===i.entityId));sheets.Evidence=rows.flatMap(r=>(r.assurance.evidenceRequirements||[]).map(e=>({recordId:r.recordId,resultId:r.id,...e})));sheets.TraceReferences=rows.filter(r=>r.type==='water').map(r=>({structureRecordId:r.recordId,route:r.route,traceRows:r.calculation.dailyTrace?.length||0,formulaIds:r.calculation.formulaIds,qa:r.calculation.qa}));sheets.Versions=Object.entries(model.pack.audit.versionIds).map(([key,value])=>({key,value}));}return sheets;}
export async function zipWithManifest(files,metadata){const z=new globalThis.JSZip(),manifest=[];for(const [name,content] of Object.entries(files)){z.file(name,content);const bytes=typeof content==='string'?new TextEncoder().encode(content):content instanceof Blob?new Uint8Array(await content.arrayBuffer()):new Uint8Array(content);const hash=await crypto.subtle.digest('SHA-256',bytes);manifest.push({file:name,sizeBytes:bytes.byteLength,sha256:[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')});}z.file('MANIFEST.json',JSON.stringify({metadata,files:manifest},null,2));return z.generateAsync({type:'blob'});}
export async function auditZip(model){return zipWithManifest({'standard-audit.json':JSON.stringify(model.pack.audit,null,2),'default-result-entities.json':JSON.stringify(design5Rows(model,{}),null,2),'product-correction-log.json':JSON.stringify(model.pack.corrections.map(({originalValue,previousValue,correctedValue,reason,...c})=>({...c,valuesAndFreeTextRedacted:true})),null,2),'README.txt':'Standard audit is the protected E09 export. Default result entities are product projections of prepared truth. Correction values and free-text reasons are redacted. Original bytes, participant names/tokens and source notes are excluded.'},{runId:model.pack.audit.runManifest.runId,scope:'full run',methodology:model.pack.audit.versionIds});}
